# Generated by Django 3.2.7 on 2023-09-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_data_entry_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorFreq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('freq', models.CharField(max_length=200, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='data_entry',
            new_name='DataEntry',
        ),
        migrations.DeleteModel(
            name='color_freq',
        ),
    ]
